"""Derive a display theme patch from the stock FIRMWARE and IMAGE_DATA sections."""

from __future__ import annotations

import hashlib
import struct
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Final

from thd75_fw import images
from thd75_fw.patch import SectionHashes, parse_patch

from .colour import colourise, colourise_rgb, invert, rgb_to_rgb565
from .palettes import load_palette_table, pack_palette, read_palette
from .png import find_chunk, is_indexed_8bit, palette, replace_palette
from .toml_out import ByteRun, PatchTomlContent, render_patch_toml
from .twins import (
    UI_TABLE_WINDOW,
    V103_ROLE_OVERRIDES,
    Role,
    ThemeError,
    assign_roles,
    closest_black_twin,
    collect_evidence,
    find_twin_groups,
)

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence

    from thd75_fw.patch import Patch

    from .colour import RGB

__all__: list[str] = [
    "BLACK_SOURCE_PAIRS",
    "DEFAULT_DESCRIPTION_TEMPLATE",
    "DEFAULT_NAME",
    "DEFAULT_TARGET",
    "IMAGE_DATA_VERSION_EXPECT",
    "IMAGE_DATA_VERSION_OFFSET",
    "IMAGE_DATA_VERSION_VALUE",
    "IN_PLACE_PAIRS",
    "LABEL_EXPECT",
    "LABEL_OFFSET",
    "LABEL_SLOT",
    "LABEL_VALUE",
    "PAIR_OFFSET",
    "TEXT_PALETTE_BLACK_OFFSET",
    "TEXT_PALETTE_ENTRIES",
    "TEXT_PALETTE_WHITE_OFFSET",
    "V103_TEXT_PALETTE_BLACK",
    "ByteRun",
    "ThemeBuild",
    "ThemeError",
    "ThemeOptions",
    "ThemeReport",
    "build_theme",
]

FIRMWARE = "FIRMWARE"
IMAGE_DATA = "IMAGE_DATA"

TEXT_PALETTE_BLACK_OFFSET: int = 0x15FAFC
TEXT_PALETTE_WHITE_OFFSET: int = 0x15FB10
TEXT_PALETTE_ENTRIES: int = 10
V103_TEXT_PALETTE_BLACK: tuple[int, ...] = (
    0xFFFF,
    0x0000,
    0xF800,
    0xFFFF,
    0x869F,
    0x528A,
    0xFFFF,
    0x3314,
    0x5C89,
    0x0000,
)
"""Black-scheme text colours by style in V1.03 (disp_draw_glyph, palette kind 14)."""

LABEL_OFFSET: int = 0x8798
LABEL_SLOT: int = 40
LABEL_EXPECT: bytes = b"White\x00"
LABEL_VALUE: bytes = b"Orange"

IMAGE_DATA_VERSION_OFFSET: int = 0
IMAGE_DATA_VERSION_EXPECT: bytes = b"1.00.02.00"
IMAGE_DATA_VERSION_VALUE: bytes = b"1.00.02.01"
"""The loader's SETUP compares these header bytes with the KEX ``$VA``; a
changed value makes it write IMAGE_DATA instead of reporting it current."""

BLACK_SOURCE_PAIRS: tuple[int, ...] = (0, 1, 2, 3, 5)
"""Palette pairs whose images are scheme-independent: White set := colourise(Black set)."""
IN_PLACE_PAIRS: tuple[int, ...] = (7, 8)
"""Palette pairs used by the per-scheme digit renders (kinds 12 and 13): transformed in place."""
PAIR_OFFSET: int = 9

DEFAULT_NAME: str = "orange-on-black"
DEFAULT_TARGET: str = (
    "TH-D75 V1.03 FIRMWARE with stock display tables (stock or normal-GM family)"
)
DEFAULT_DESCRIPTION_TEMPLATE: str = """
Orange-on-black display theme for menu 906 "Background Color". Re-skins the
"White" option: the White palette set, the White text palette and
the {twins} white-scheme icon twin{plural} take the Black scheme's colours
with every white and grey tone recoloured to
{colour}; the two per-scheme digit palettes are inverted in place; the
option label becomes "Orange"; the IMAGE_DATA header version becomes
1.00.02.01 so the loader writes the section. Applies to stock V1.03 and to
any firmware that leaves the display tables and IMAGE_DATA stock (the
normal-GM family). Generated by thd75-theme.
"""


@dataclass(frozen=True, slots=True)
class ThemeReport:
    """What the build touched, for the CLI summary."""

    text_palette_entries: int
    label_changed: bool
    palettes_changed: tuple[int, ...]
    twin_groups: int
    twins_recoloured: int
    twins_from_overrides: tuple[int, ...]
    image_version_bumped: bool
    firmware_bytes: int
    image_data_bytes: int


@dataclass(frozen=True, slots=True)
class ThemeBuild:
    """A built theme: its runs, pins, rendered TOML, parsed patch and report."""

    runs: tuple[ByteRun, ...]
    section_hashes: tuple[SectionHashes, ...]
    toml: str
    patch: Patch
    report: ThemeReport
    patched_image_data: bytes


@dataclass(frozen=True, slots=True, kw_only=True)
class ThemeOptions:
    """Patch metadata and twin-role inputs for :func:`build_theme`.

    The defaults build the catalog ``orange-on-black`` patch's metadata for
    stock V1.03, so ``ThemeOptions()`` changes nothing.

    Attributes:
        name: Patch name written to the TOML.
        target_firmware: ``target_firmware`` text written to the TOML.
        description_template: ``str.format`` template for the description,
            filled with ``twins``, ``plural`` and ``colour``.
        overrides: Twin roles fixed in advance, by image index, where the
            FIRMWARE evidence alone cannot decide them.
        evidence_window: FIRMWARE flat-offset range ``(start, end)`` scanned
            for the display tables that vote on twin roles.

    """

    name: str = DEFAULT_NAME
    target_firmware: str = DEFAULT_TARGET
    description_template: str = DEFAULT_DESCRIPTION_TEMPLATE
    overrides: Mapping[int, Role] = field(default_factory=lambda: V103_ROLE_OVERRIDES)
    evidence_window: tuple[int, int] = UI_TABLE_WINDOW


#: The stock V1.03 ``orange-on-black`` metadata and role inputs, the
#: :func:`build_theme` default.
_DEFAULT_THEME_OPTIONS: Final[ThemeOptions] = ThemeOptions()


def _firmware_runs(firmware: bytes, theme: RGB) -> tuple[list[ByteRun], int, bool]:
    palette_end = TEXT_PALETTE_BLACK_OFFSET + 4 * TEXT_PALETTE_ENTRIES
    if len(firmware) < max(palette_end, LABEL_OFFSET + LABEL_SLOT):
        msg = (
            f"FIRMWARE image is {len(firmware)} bytes, too short for the V1.03 "
            "display tables"
        )
        raise ThemeError(msg)
    black = struct.unpack_from(
        f"<{TEXT_PALETTE_ENTRIES}H", firmware, TEXT_PALETTE_BLACK_OFFSET
    )
    if black != V103_TEXT_PALETTE_BLACK:
        msg = (
            "FIRMWARE does not carry the V1.03 Black text palette at "
            f"0x{TEXT_PALETTE_BLACK_OFFSET:X}"
        )
        raise ThemeError(msg)
    slot = firmware[LABEL_OFFSET : LABEL_OFFSET + LABEL_SLOT]
    if not slot.startswith(LABEL_EXPECT):
        msg = f"menu label slot at 0x{LABEL_OFFSET:X} does not read 'White'"
        raise ThemeError(msg)
    runs: list[ByteRun] = []
    label_run = ByteRun(
        FIRMWARE, LABEL_OFFSET, slot, LABEL_VALUE + slot[len(LABEL_VALUE) :]
    )
    if label_run.changed():
        runs.append(label_run)
    expect = firmware[TEXT_PALETTE_BLACK_OFFSET:palette_end]
    new_white = tuple(colourise(value, theme) for value in black)
    text_run = ByteRun(
        FIRMWARE,
        TEXT_PALETTE_BLACK_OFFSET,
        expect,
        expect[:20] + pack_palette(new_white),
    )
    entries_changed = 0
    if text_run.changed():
        runs.append(text_run)
        current_white = struct.unpack_from(
            f"<{TEXT_PALETTE_ENTRIES}H", firmware, TEXT_PALETTE_WHITE_OFFSET
        )
        entries_changed = sum(
            1 for old, new in zip(current_white, new_white, strict=True) if old != new
        )
    return runs, entries_changed, bool(label_run.changed())


def _version_run(image_data: bytes) -> ByteRun:
    """Bump the IMAGE_DATA header version so the loader's SETUP check writes it."""
    end = IMAGE_DATA_VERSION_OFFSET + len(IMAGE_DATA_VERSION_EXPECT)
    current = image_data[IMAGE_DATA_VERSION_OFFSET:end]
    if current != IMAGE_DATA_VERSION_EXPECT:
        msg = (
            f"IMAGE_DATA header version is {current!r}, expected "
            f"{IMAGE_DATA_VERSION_EXPECT!r}"
        )
        raise ThemeError(msg)
    return ByteRun(
        IMAGE_DATA, IMAGE_DATA_VERSION_OFFSET, current, IMAGE_DATA_VERSION_VALUE
    )


def _palette_runs(image_data: bytes, theme: RGB) -> tuple[list[ByteRun], list[int]]:
    table = load_palette_table(image_data)
    runs: list[ByteRun] = []
    changed: list[int] = []
    for pair in (*BLACK_SOURCE_PAIRS, *IN_PLACE_PAIRS):
        white_index = pair + PAIR_OFFSET
        black = read_palette(image_data, table, pair)
        white = read_palette(image_data, table, white_index)
        if pair in BLACK_SOURCE_PAIRS:
            if len(black) != len(white):
                msg = (
                    f"palette pair {pair}/{white_index}: {len(black)} vs "
                    f"{len(white)} entries"
                )
                raise ThemeError(msg)
            new = tuple(colourise(value, theme) for value in black)
        else:
            new = tuple(
                colourise(value, theme)
                if index < len(black) and black[index] == value
                else invert(value, theme)
                for index, value in enumerate(white)
            )
        start, end = table.span(white_index)
        run = ByteRun(IMAGE_DATA, start, image_data[start:end], pack_palette(new))
        if run.changed():
            runs.append(run)
            changed.append(white_index)
    return runs, changed


def _twin_runs(
    firmware: bytes,
    image_data: bytes,
    theme: RGB,
    overrides: Mapping[int, Role],
    window: tuple[int, int],
) -> tuple[list[ByteRun], int, int, list[int]]:
    database = images.load(image_data)
    pngs = {
        image.index: image.data
        for image in database.images
        if is_indexed_8bit(image.data)
    }
    offsets = {image.index: image.offset for image in database.images}
    groups = find_twin_groups(pngs)
    evidence = collect_evidence(firmware, groups, window)
    roles = assign_roles(groups, evidence, overrides)
    runs: list[ByteRun] = []
    recoloured = 0
    from_overrides: list[int] = []
    for group in groups:
        for white in group.members:
            if roles[white] is not Role.WHITE:
                continue
            black = closest_black_twin(white, group, roles, pngs)
            black_entries = palette(pngs[black])
            white_entries = palette(pngs[white])
            new_entries = [
                colourise_rgb(black_entries[index], theme)
                if index < len(black_entries)
                else entry
                for index, entry in enumerate(white_entries)
            ]
            new_png = replace_palette(pngs[white], new_entries)
            plte = find_chunk(pngs[white], b"PLTE")
            start = offsets[white] + plte.data_offset
            end = offsets[white] + plte.crc_offset + 4
            run = ByteRun(
                IMAGE_DATA,
                start,
                image_data[start:end],
                new_png[plte.data_offset : plte.crc_offset + 4],
            )
            if run.changed():
                runs.append(run)
                recoloured += 1
                if white in overrides:
                    from_overrides.append(white)
    return runs, len(groups), recoloured, from_overrides


def _apply_runs(image: bytes, runs: Sequence[ByteRun], section: str) -> bytes:
    out = bytearray(image)
    for run in runs:
        if run.section != section:
            continue
        if bytes(out[run.offset : run.offset + len(run.expect)]) != run.expect:
            msg = f"{section} run at 0x{run.offset:X} does not match the source image"
            raise ThemeError(msg)
        out[run.offset : run.offset + len(run.value)] = run.value
    return bytes(out)


def build_theme(
    firmware: bytes,
    image_data: bytes,
    theme: RGB,
    options: ThemeOptions = _DEFAULT_THEME_OPTIONS,
) -> ThemeBuild:
    """Derive the theme patch for ``theme`` from stock-shaped sections.

    Args:
        firmware: The stock-shaped FIRMWARE section image.
        image_data: The stock-shaped IMAGE_DATA section image.
        theme: The theme colour every white and grey tone becomes.
        options: Patch metadata and twin-role inputs; the default is the
            catalog ``orange-on-black`` patch for stock V1.03.

    Raises:
        ThemeError: if the sections do not carry the expected display tables,
            or a twin group's roles cannot be resolved.
        ValueError: if the derived patch fails the patch model's validation.

    """
    firmware_runs, text_entries, label_changed = _firmware_runs(firmware, theme)
    palette_runs, palettes_changed = _palette_runs(image_data, theme)
    twin_runs, group_count, recoloured, from_overrides = _twin_runs(
        firmware, image_data, theme, options.overrides, options.evidence_window
    )
    version_run = _version_run(image_data)
    runs = (*firmware_runs, version_run, *palette_runs, *twin_runs)
    patched_image_data = _apply_runs(image_data, runs, IMAGE_DATA)
    section_hashes = (
        SectionHashes(
            section=IMAGE_DATA,
            source_sha256=hashlib.sha256(image_data).hexdigest(),
            result_sha256=hashlib.sha256(patched_image_data).hexdigest(),
            version=IMAGE_DATA_VERSION_VALUE.decode("ascii"),
        ),
    )
    red, green, blue = theme
    description = options.description_template.format(
        twins=recoloured,
        plural="" if recoloured == 1 else "s",
        colour=f"RGB {red},{green},{blue} (RGB565 0x{rgb_to_rgb565(theme):04X})",
    )
    change_count = sum(run.changed() for run in runs)
    toml = render_patch_toml(
        PatchTomlContent(
            name=options.name,
            description=description,
            target_firmware=options.target_firmware,
            change_count=change_count,
            section_hashes=section_hashes,
            runs=runs,
        )
    )
    patch = parse_patch(toml)
    report = ThemeReport(
        text_palette_entries=text_entries,
        label_changed=label_changed,
        palettes_changed=tuple(palettes_changed),
        twin_groups=group_count,
        twins_recoloured=recoloured,
        twins_from_overrides=tuple(from_overrides),
        image_version_bumped=bool(version_run.changed()),
        firmware_bytes=sum(run.changed() for run in runs if run.section == FIRMWARE),
        image_data_bytes=sum(
            run.changed() for run in runs if run.section == IMAGE_DATA
        ),
    )
    return ThemeBuild(
        runs=runs,
        section_hashes=section_hashes,
        toml=toml,
        patch=patch,
        report=report,
        patched_image_data=patched_image_data,
    )
